name: Mirror‑to‑GitCode
on:
  push:
    branches: [ main ]
jobs:
  mirror_task:
    runs‑on: ubuntu‑latest
    steps:
      - uses: Yikun/hub‑mirror‑action@master
        with:
          src: github/qldwj/Kazuminb6Rules
          dst: gitcode/qldwi/Kazuminb6Rules
          dst_token: ${{ secrets.GITCODE_TOKEN }}
